
GET http://localhost:3000/partners HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/partners HTTP/1.1
content-type: application/json

{
    "relativeLatitude": "51.5144636",
    "relativeLongitude": "-0.142571", 
    "range" : "6820.162587417329",
    "key" : "organization"
}
