
GET http://localhost:3000/partners HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/partners HTTP/1.1
content-type: application/json

{
    "relativeLatitude": "51.5144636",
    "relativeLongitude": "-0.142571", 
    "range" : "6820.162587417329",
    "key" : "organization"
}

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name" : "Souraya Nasser",
    "password" : "pass123", 
    "email" : "surayanasser18@gmail.com",
    "birthday" : "1960-10-17T00:00:00",
    "usertype" : "Student"
}

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name" : "Julian Julian",
    "password" : "pass123", 
    "email" : "julianjulian@gmail.com",
    "birthday" : "1960-01-01T00:00:00",
    "usertype" : "Professor"
}

###
PATCH http://localhost:3000/users/5f526e84d21ca31ee4f32a7e HTTP/1.1
content-type: application/json

{
    "name" : "Souraya Nasser",
    "password" : "snasser123", 
    "email" : "surayanasser18@gmail.com",
    "birthday" : "1994-10-17T22:00:00"
}

###

PATCH http://localhost:3000/users/5f527fc9026ab966101a0668 HTTP/1.1
content-type: application/json

{
    "name" : "Julian Julian",
    "password" : "pass123", 
    "email" : "julianjulian@gmail.com",
    "birthday" : "1960-01-22:00:00",
    "usertype" : "Professor"
}

###

PATCH http://localhost:3000/users/5f527fc9026ab966101a0668 HTTP/1.1
content-type: application/json

{
    "name" : "Julian Julian",
    "password" : "julian123", 
    "email" : "j,;/ulianjulian12@gmail.com",
    "birthday" : "1960-01-22:00:00"
}

###

DELETE http://localhost:3000/users/5f527eb1ee2c2e6a30da3924 HTTP/1.1
content-type: application/json

